const db = require('../database/db');
const path = require('path');
const fs = require('fs');

const ALLOWED_TABLES = ['propietarios', 'mascotas', 'historial_medico', 'citas', 'usuarios', 'inventario', 'movimientos_inventario'];

function validateTableName(table) {
  if (!ALLOWED_TABLES.includes(table)) {
    throw new Error(`Tabla no permitida: ${table}`);
  }
  if (!/^[a-z_]+$/.test(table)) {
    throw new Error(`Nombre de tabla inválido: ${table}`);
  }
  return table;
}

function validateBackupPath(filePath) {
  if (typeof filePath !== 'string' || !filePath.trim()) {
    throw new Error('Ruta de archivo inválida');
  }
  const resolved = path.resolve(filePath);
  if (!resolved.toLowerCase().endsWith('.sql')) {
    throw new Error('El archivo de respaldo debe tener extensión .sql');
  }
  return resolved;
}

function escapeIdentifier(name) {
  return '`' + String(name).replace(/`/g, '``') + '`';
}

function escapeValue(val) {
  if (val === null || val === undefined) return 'NULL';
  if (Buffer.isBuffer(val)) return `'${val.toString('hex')}'`;
  if (typeof val === 'number') return val;
  if (val instanceof Date) return `'${formatSqlDate(val)}'`;
  const str = String(val)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "''")
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')
    .replace(/\t/g, '\\t');
  return `'${str}'`;
}

function pad2(n) {
  return String(n).padStart(2, '0');
}

function formatSqlDate(d) {
  const date = `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
  const h = d.getHours();
  const m = d.getMinutes();
  const s = d.getSeconds();
  if (h === 0 && m === 0 && s === 0) return date;
  return `${date} ${pad2(h)}:${pad2(m)}:${pad2(s)}`;
}

async function exportBackup(filePath, userId) {
  const safePath = validateBackupPath(filePath);
  let sql = '-- Backup generated by Sistema Veterinario\n-- Date: ' + new Date().toISOString() + '\n\n';
  sql += 'SET FOREIGN_KEY_CHECKS=0;\n\n';

  for (const table of ALLOWED_TABLES) {
    const rows = await db.query(`SELECT * FROM ${escapeIdentifier(table)}`);
    if (rows.length === 0) continue;

    const columns = Object.keys(rows[0]);
    sql += `TRUNCATE TABLE ${escapeIdentifier(table)};\n`;

    for (const row of rows) {
      const values = columns.map((col) => escapeValue(row[col]));
      const escapedCols = columns.map((col) => escapeIdentifier(col)).join(', ');
      sql += `INSERT INTO ${escapeIdentifier(table)} (${escapedCols}) VALUES (${values.join(', ')});\n`;
    }
    sql += '\n';
  }

  sql += 'SET FOREIGN_KEY_CHECKS=1;\n';
  fs.writeFileSync(safePath, sql, 'utf8');

  await db.auditLog(userId, 'EXPORT_BACKUP', 'sistema', null, null, { filePath: safePath });
  db.log.info('Backup exported', { userId, filePath: safePath });
  return true;
}

async function importBackup(filePath, userId) {
  const safePath = validateBackupPath(filePath);
  if (!fs.existsSync(safePath)) throw new Error('Archivo no encontrado');
  const sql = fs.readFileSync(safePath, 'utf8');

  const cleanedSql = sql
    .replace(/^\s*--.*$/gm, '')
    .replace(/^\s*#.*$/gm, '')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .trim();

  const statements = cleanedSql
    .split(/;\s*\n/)
    .map((s) => s.trim())
    .filter((s) => s.length > 0);

  for (const stmt of statements) {
    const normalized = stmt.toUpperCase();
    if (!/^(TRUNCATE|INSERT|SET)/.test(normalized)) {
      continue;
    }

    if (normalized.startsWith('SET')) {
      if (!/^SET\s+FOREIGN_KEY_CHECKS\s*=\s*[01]\s*$/i.test(stmt.trim())) {
        continue;
      }
      await db.query(stmt);
      continue;
    }

    if (stmt.includes(';')) {
      throw new Error('Statement con múltiples sentencias no permitido en backup');
    }

    if (normalized.startsWith('TRUNCATE')) {
      const match = stmt.match(/^TRUNCATE(?:\s+TABLE)?\s+`?([a-z_]+)`?\s*$/i);
      if (!match) throw new Error('TRUNCATE inválido en backup');
      validateTableName(match[1]);
    } else if (normalized.startsWith('INSERT')) {
      const match = stmt.match(/^INSERT(?:\s+INTO)?\s+`?([a-z_]+)`?\s*\(([^)]+)\)\s*VALUES\s*\(/i);
      if (!match) throw new Error('INSERT inválido en backup');
      validateTableName(match[1]);
      const cols = match[2].split(',').map(c => c.trim().replace(/^`|`$/g, ''));
      for (const col of cols) {
        if (!/^[a-z_][a-z0-9_]*$/i.test(col)) {
          throw new Error(`Nombre de columna inválido en backup: ${col}`);
        }
      }
    }

    await db.query(stmt);
  }

  await db.auditLog(userId, 'IMPORT_BACKUP', 'sistema', null, null, { filePath: safePath });
  db.log.info('Backup imported', { userId, filePath: safePath });
  return true;
}

module.exports = { exportBackup, importBackup };
