Object.defineProperty(window, 'api', {
  value: {
    getUser: () => null,
    hasRole: () => false,
    login: jest.fn(),
    logout: jest.fn(),
    getMe: jest.fn(),
    setUser: jest.fn(),
    getPropietarios: jest.fn(),
    getPropietario: jest.fn(),
    createPropietario: jest.fn(),
    updatePropietario: jest.fn(),
    deletePropietario: jest.fn(),
    getMascotas: jest.fn(),
    getMascota: jest.fn(),
    createMascota: jest.fn(),
    updateMascota: jest.fn(),
    deleteMascota: jest.fn(),
    getHistorial: jest.fn(),
    createHistorial: jest.fn(),
    updateHistorial: jest.fn(),
    deleteHistorial: jest.fn(),
    getCitasByDate: jest.fn(),
    getCitasByMonth: jest.fn(),
    createCita: jest.fn(),
    updateCita: jest.fn(),
    deleteCita: jest.fn(),
    getMascotasForCitas: jest.fn(),
    getDashboardSummary: jest.fn(),
    getUsuarios: jest.fn(),
    getUsuario: jest.fn(),
    changePassword: jest.fn(),
    createUsuario: jest.fn(),
    updateUsuario: jest.fn(),
    deleteUsuario: jest.fn(),
    getInventario: jest.fn(),
    getInventarioItem: jest.fn(),
    createInventarioItem: jest.fn(),
    updateInventarioItem: jest.fn(),
    deleteInventarioItem: jest.fn(),
    getInventarioMovimientos: jest.fn(),
    registrarMovimientoInventario: jest.fn(),
    checkReminders: jest.fn(),
    getAuditLog: jest.fn(),
    globalSearch: jest.fn(),
    exportBackup: jest.fn(),
    importBackup: jest.fn(),
    selectFile: jest.fn(),
    saveFile: jest.fn(),
    selectPhoto: jest.fn(),
    getPhotoDataUrl: jest.fn(),
    notifyDesktop: jest.fn(),
  },
  writable: true,
});
